# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Update app icons"
  lane :update_icons do
    appicon(
      appicon_image_file: "/Users/tonyblum/VSProjects/westway_feed/assets/appstore.png",
      appicon_devices: [:iphone, :ipad, :ios_marketing],
      appicon_path: "./Runner/Assets.xcassets"
    )
  end
end


